#!/usr/bin/env python3
# coding: utf-8

import sys
from pathlib import Path


def main():
	num_rcts = 718

	for path in sorted(Path(".").rglob("res*")):
		num_neg_vals = 0
		with open(path) as f:
			for line in f:
				if " -" in line:
					num_neg_vals += 1

		pct_neg_vals = round(num_neg_vals/num_rcts*100, 1)
		print(f"File {path} contains {pct_neg_vals}% negative values.")


if __name__ == '__main__':
	main()