#!/usr/bin/env python3
# coding: utf-8

import sys
import os
from pathlib import Path
import argparse

try:
  import pandas as pd
except ModuleNotFoundError:
  sys.exit("Module 'pandas' not installed. Exiting.")

try:
  import numpy as np
except ModuleNotFoundError:
  sys.exit("Module 'numpy' not installed. Exiting.")



def md(data, axis=None):
  return np.mean(data, axis)

def mad(data, axis=None):
  return np.mean(np.absolute(data - np.mean(data, axis)), axis)

def mae(data):
  return np.mean(np.absolute(data))

def rmsd(data):
  return np.sqrt(np.mean(np.square(data)))


def getOmegas(test_file="NCIBLIND10/1-A/job.out"):
  count_criter = 0
  o = []

  path = Path(test_file)

  if not path.is_file():
    print(f"WARNING! Test file '{test_file}' not found. Using default omegas.")
    omegas = [100, 150, 200, 250, 300, 350, 400, 450]
    return omegas[::-1]


  with open(path) as f:
    for line in f:
      if line.startswith("omega"):
        o.append(int(line.strip().split()[1]))

      if "Convergence criterion met" in line:
        count_criter += 1

    # check convergence for my multijob
    if count_criter != len(o):
      sys.exit(f"Convergence not reached in {test_file}.")

  return o


def getDataTestSet(set_name, omegas, num_decimals=4):
  factor = 627.50947428
  num_jobs = len(omegas)

  df = pd.read_csv(f"{set_name}/ref.csv", dtype={"dimer": str})
  set_list = df["dimer"].to_list()
  set_ref = df["reference"].to_list()

  data = []

  for i, d in enumerate(set_list):
    dimer = f"{set_name}/{d}"

    if set_name == "S22x5":
      monoA = f"{set_name}/{d.split('_')[0]}A"
      monoB = f"{set_name}/{d.split('_')[0]}B"
    elif set_name == "S66x8":
      monoA = f"{set_name}/{d.split('.')[0]}A"
      monoB = f"{set_name}/{d.split('.')[0]}B"
    elif set_name == "NCIBLIND10":
      if int(d) < 100:
        monoA = f"NCIBLIND10/{d[0]}A"
        monoB = f"NCIBLIND10/{d[0]}B"
      else:
        monoA = "NCIBLIND10/10A"
        monoB = "NCIBLIND10/10B"


    e_dimer = []
    o = []
    count_criter = 0
    with open(Path(f"{dimer}/job.out")) as f:
      for line in f:
        if line.startswith("omega"):
          o.append(int(line.strip().split()[1]))

        if "Convergence criterion met" in line:
          energy = line.split()[1]
          e_dimer.append(float(energy))
          count_criter += 1

      # check convergence for my multijob
      if count_criter != num_jobs:
        sys.exit(f"Convergence not reached in {system}.")

      # check order of omegas
      if o != omegas:
        sys.exit("Order of omegas wrong!")

    e_monoA = []
    o = []
    count_criter = 0
    with open(Path(f"{monoA}/job.out")) as f:
      count_criter = 0

      for line in f:
        if line.startswith("omega"):
          o.append(int(line.strip().split()[1]))

        if "Convergence criterion met" in line:
          energy = line.split()[1]
          e_monoA.append(float(energy))
          count_criter += 1

      # check convergence for my multijob
      if count_criter != num_jobs:
        sys.exit(f"Convergence not reached in {system}.")

      # check order of omegas
      if o != omegas:
        sys.exit("Order of omegas wrong!")


    e_monoB = []
    o = []
    count_criter = 0
    with open(Path(f"{monoB}/job.out")) as f:
      count_criter = 0

      for line in f:
        if line.startswith("omega"):
          o.append(int(line.strip().split()[1]))

        if "Convergence criterion met" in line:
          energy = line.split()[1]
          e_monoB.append(float(energy))
          count_criter += 1

      # check convergence for my multijob
      if count_criter != num_jobs:
        sys.exit(f"Convergence not reached in {system}.")

      # check order of omegas
      if o != omegas:
        sys.exit("Order of omegas wrong!")


    e = (np.asarray(e_dimer) - np.asarray(e_monoA) - np.asarray(e_monoB))*factor - set_ref[i]
    data.append([dimer] + e.tolist())

  return data


def stat_no_d4(args):
  num_decimals = 4
  
  omegas = getOmegas()
  print(f"Found {len(omegas)} omega values: {omegas}\n")

  # get data
  s22x5 = getDataTestSet("S22x5", omegas)
  s66x8 = getDataTestSet("S66x8", omegas)
  nci = getDataTestSet("NCIBLIND10", omegas)

  # chain data together
  data = s22x5 + s66x8 + nci

  # show data
  data = np.asarray(data)
  cols = ["system"] + omegas
  df = pd.DataFrame(columns=cols, data=data)

  cols = [i for i in df.columns if i != "system"]
  for col in cols:
    df[col] = pd.to_numeric(df[col])

  df = df.round(num_decimals)
  
  print(f"Data: E_int - E_ref for {Path.cwd().name}")
  print("---------------------------------")
  print(df)


  ####################
  ## Get Statistics ##
  ####################

  MDs = []
  MADs = []
  RMSDs = []

  for col in cols:
    MDs.append(md(df[col]))
    MADs.append(mad(df[col]))
    RMSDs.append(rmsd(df[col]))

  data = []
  for i, omega in enumerate(omegas):
    data.append([omega, MDs[i], MADs[i], RMSDs[i],])

  df = pd.DataFrame(columns=["omega", "MD", "MAD", "RMSD"], data=data)

  cols = [i for i in df.columns if i != "measure"]
  for col in cols:
    df[col] = pd.to_numeric(df[col])

  df = df.round(num_decimals)
  print("\n")
  print("Statistics")
  print("----------")
  print(df.to_string(index=False))

  if args.save:
    out_file = f"stat_{Path.cwd().name.lower()}_nod4.csv"
    save_loc = os.path.join(os.path.realpath("."), out_file)
    df.to_csv(save_loc, index=False)
    print("\nSaved data to {}.".format(save_loc))
  

def stat_fit(args):
  omegas = [100, 150, 200, 250, 300, 350, 400, 450]
  MDs = []
  MADs = []
  RMSDs = []

  for filename in sorted(Path(".").glob("*d4*.out")):
    paramline = False
    found = False
    with open(filename) as f:
      for line in f:
        if line.startswith("Final run:"):
          paramline = True
          found = True
          continue

        if paramline:
          l = line.strip().split()
          MDs.append(l[5])
          MADs.append(l[7])
          RMSDs.append(l[9])
          paramline = False

    if not found:
      print(f"WARNING! No parameters found in {filename}.")
      MDs.append("NaN")
      MADs.append("NaN")
      RMSDs.append("NaN")

  data = []
  for i, omega in enumerate(omegas):
    data.append([omega, MDs[i], MADs[i], RMSDs[i],])

  cols = ["omega", "MD", "MAD", "RMSD"]
  df = pd.DataFrame(columns=cols, data=data)
  print(df.to_string(index=False))

  if args.save:
    out_file = f"stat_{Path.cwd().name.lower()}_fit.csv"
    save_loc = os.path.join(os.path.realpath("."), out_file)
    df.to_csv(save_loc, index=False)
    print("\nSaved data to {}.".format(save_loc))


def main():
  parser = argparse.ArgumentParser(description="Get statistical data.")
  parser.add_argument("-f", "--fit", action="store_true", help="Statistics from fit job.")
  parser.add_argument("-s", "--save", action="store_true", help="Save output.")
  args = parser.parse_args()

  if args.fit:
    stat_fit(args)
  else:
    stat_no_d4(args)
  

if __name__ == '__main__':
  main()