#!/usr/bin/env python3
# coding: utf-8

# HOW IT WORKS:
# Searches recursively in current directory for all *.out files.
# Creates data.csv in current directory (if pandas available)

import glob
import os
import sys


save = True
save_loc = os.path.join(os.path.realpath("."), "data.csv")


def main():
  data = []

  for filename in getFileList():
    rem = False
    rem_dict = {}

    with open(filename, errors='ignore') as f:
      count_criter = 0
      num_jobs = 1
      for i, line in enumerate(f):

        # only entered if previous line was start of rem block
        if rem == True:
          # turn false again if end encountered, otherwise do stuff
          if line.startswith("$end"):
            rem = False
          else:
            rem_dict[line.strip().split()[0]] = line.strip().split()[1]


        # turns true if rem block is hit
        if line.startswith("$rem"): 
          rem = True
          continue


        # get number of jobs in multijob file
        if line.startswith("User input:") and "of" in line:
          num_jobs = line.strip().split()[-1]


        if "shells" in line and "basis functions" in line:
          nbas = line.split("shells and")[1].split("basis functions")[0].strip()


        if line.startswith(" SCF time:   CPU"):
          walltime = line.split("wall")[1].strip()
          walltime = walltime[:-1]


        # append data in line furthest down
        if " Total energy in the final basis set =" in line:
          energy = line.split("=")[1].strip()
          data.append([filename, energy, nbas, walltime] + list(rem_dict.values()))


      # check convergence for my multijob
      if count_criter != num_jobs:
        sys.exit()

  ########################################      
  ## data collection (outside of loop!) ##
  ########################################

  cols = ["filename", "energy", "nbas", "time"] + list(rem_dict.keys())

  try:
    import pandas as pd
    df = pd.DataFrame(columns=cols, data=data)

    if save and save_loc:
      df.to_csv(save_loc, index=False)
      print("Saved data to {}.".format(save_loc))

    print("")
    print(df)

  except ModuleNotFoundError:
    print("Module 'pandas' not found. Trying to use numpy...")

    # fallback: using numpy for saving data to csv
    try:
      import numpy as np

      # add col names to list
      data.insert(0, cols)

      if is_numpy and save and save_loc:
        np.savetxt(save_loc, data, fmt='%s', delimiter="\t")
        print("Saved data to {}.".format(save_loc))
      else:
        print("Saving failed.")
    except ModuleNotFoundError:
      print("Module 'numpy' not found. Data will not be saved.")


    print("")
    print('\n'.join(' '.join(str(x) for x in row) for row in data))


def getFileList():
  filelist = []
  try:
    for file in glob.glob('./**/*.out', recursive=True):
      if file.endswith(".out"):
        filelist.append(file)

    if len(filelist) == 0:
      print("No files found.", filelist)
      sys.exit()

    return filelist
  except Exception as e:
    print(e)
    sys.exit()


if __name__ == '__main__':
  main()
